### Sign Up a user
POST http://localhost:4000/users
content-type: application/json

{
  "username": "misaelburboa",
  "email": "cmburboa@gmail.com",
  "password": "MySuperCoolPass!123",
  "name": "Misael Burboa",
  "phone": "6621836340"
}