### Sign Up a user
POST http://localhost:4000/auth/signup
content-type: application/json

{
  "username": "misaelburboa",
  "email": "cmburboa@gmail.com",
  "name": "Misael Burboa",
  "phone": "6621836340"
}