
### Retrieve list of events
GET http://localhost:4000/events?page=1&pageSize=1

### Retrieve a single event by id
GET http://localhost:4000/events/1

### Register an event
POST http://localhost:4000/events
content-type: application/json

{
	"name": "Reunion de Domingo",
	"date": "2021/03/18",
	"singleSeatsNumber": 24,
	"doubleSeatsNumber": 24
}

### Register to an event
POST http://localhost:4000/events/1/register
content-type: application/json

{
  "attendeeFullName": "Misael Burboa",
  "secondAttendeeFullName": "Alejandro Burboa",
  "phone1": "+526621836340",
  "seatType": "single"
}