
### Retrieve list of events
GET http://localhost:4000/events?page=1&pageSize=2

### Retrieve a single event by id
GET http://localhost:4000/events/1

### Gets the attendees are expected to asist
GET http://localhost:4000/events/1/attendees

### Register an event
POST http://localhost:4000/events
content-type: application/json

{
	"name": "Reunion de Domingo",
	"date": "2021/03/18",
	"singleSeatsNumber": 24,
	"doubleSeatsNumber": 24
}

### Retrieve a single event by id
PATCH http://localhost:4000/events/1/activate

### Retrieve a single event by id
PATCH http://localhost:4000/events/1/deactivate

### Register to an event
POST http://localhost:4000/events/1/register
content-type: application/json

{
  "attendeeFullName": "Misael Burboa",
  "secondAttendeeFullName": "Alejandro Burboa",
  "phone1": "+526621836340",
  "seatType": "single"
}

### Cancel register to an event
PATCH http://localhost:4000/register/cancel?code=CTSS7QO4